---
title: Guide to Kulchur Press
url: http://guidetokulchur.siteleaf.net
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  title:
    title: Title
    output: true
  uploads:
    title: Uploads
    output: true
Paper Stocks:
- type: 35LB Vellum
  mutliplier: ".023"
  multiplier: ".026"
Field name:
- 
