baseurl: ''
permalink: pretty
markdown: rdiscount
port: 3200
host: 127.0.0.1
mediapath: "media"
about: >
  Working in the tradition of independent presses since its inception, gtk press
  publishes works of theory, fiction, poetry, madness, economics, satire, sexuality,
  science fiction, activism and confession through several print projects. Gtk press
  is a cooperative print workshop interested in melding high and low forms of cultural
  expression into a nuanced and polemical vision of the present.
paypal:
  email: clevelandtapes@yahoo.com
defaultphoto: "https://placeholdit.imgix.net/~text?txtsize=42&txt=Image+Coming+Soon&w=600&h=400"
defaultcover: "main-cover.jpg"
collections:
  titles:
    output: true
    scope:
      path: "titles"              # an empty string here means all files
      type: "title" # applies defaults only to documents in this collection
    values:
      layout: title
      title: Title Of The Work
      permalink: "the-url-path-to-the-title"
      cover: filepath.jpg
      description: "A description of the work, with an author bio at the end"
      author: Author Name
      price: "12.00"
      releasedate: "2015-11-22"
      instock: true
      numinstock: ""
      collection: "permalink-of-the-collection-it-belongs-to"
      isbn: ""
      numpages: ""
      dimensions: 4.5x6
      published: true
  serieses:
    output: true
    scope:
      path: "titles"              # an empty string here means all files
      type: "title" # applies defaults only to documents in this collection
    values:
      title: "Vanguard Series"
      permalink: vanguard-series
      published: true
      layout: collection
      cover: vanguard-series.jpg
      submissionemail: submissions@guidetokulchurcleveland.com
      submissioninfo: |
          Submit ALL your vanguardisms
      description: |
          Giving voice to emerging writers
  journal:
    output: true
    scope:
      path: "titles"              # an empty string here means all files
      type: "title" # applies defaults only to documents in this collection
    values:
      title: "Vanguard Series"
      permalink: vanguard-series
      published: true
      layout: collection
      cover: vanguard-series.jpg
      submissionemail: submissions@guidetokulchurcleveland.com
      submissioninfo: |
          Submit ALL your vanguardisms
      description: |
          Giving voice to emerging writers
  static:
    output: true
    scope:
      path: "static"
      type: "static"
    values:
      layout: static
      published: true
      title: GTK Creative Journal Submission Guidelines
      permalink: "gtk-creative-journal-submission-guidelines"
